config/routes.rb
Rails.application.routes.draw do

  get 'orders/create'

  root                      'products#index'
  get    'signup'       =>  'users#new'
  get    'signin'       =>  'sessions#new'
  post   'signin'       =>  'sessions#create'
  delete 'signout'      =>  'sessions#destroy'
  resources :users
  resources :products
  resources :cart_items,       only: [:index, :create, :destroy, :update]
  get    'confirmation' =>  'orders#new'
  post   'orders'       =>  'orders#create'

end

app/models/cart_item.rb
class CartItem < ActiveRecord::Base
  belongs_to :user
  belongs_to :product

  validates :user_id, presence: true
  validates :product_id, presence: true
  validates :price_in_cart, presence: true
  validates :quantity_in_cart, presence: true,
              numericality: { only_integer: true, greater_than: 0 }


  def CartItem.encrypt(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  # 乱数生成
  def CartItem.new_token
    SecureRandom.urlsafe_base64
  end


  def create_lock_token
    lock_token = CartItem.encrypt(CartItem.new_token)
    self.lock_token = lock_token
  end

  def forget
    update_attribute(:lock_token, nil)
  end

end

app/controllers/cart_items_controller.rb
class CartItemsController < ApplicationController
  before_action :signed_in_user
  before_action :correct_user, only: :destroy

  def create
    product = Product.find(params[:cart_item][:product_id])
    asking_quantity = params[:cart_item][:quantity_in_cart].to_i
    cart_item = current_user.cart_items.find_or_initialize_by(product_id: product.id)

    if (cart_item.quantity_in_cart + asking_quantity) > product.stock_quantity
      flash[:danger] = "#{product.title}は在庫数が不足しています！"
      return redirect_to :back
    else
      cart_item.price_in_cart = product.price
      cart_item.quantity_in_cart += asking_quantity
      cart_item.create_lock_token
      cart_item.save
      flash[:success] = "#{product.title}を#{asking_quantity}個カートに追加しました！
      現在の#{product.title}の購入希望数は#{cart_item.quantity_in_cart}個です！"
      return redirect_to cart_items_path
    end
  end

  def index
    @cart_items = current_user.cart_items
    connect_token = ""
    @cart_items.each do |cart_item|
      if cart_item.price_in_cart != cart_item.product.price && cart_item.price_in_cart != 0
      flash.now[:warning] = "カート内の商品価格に変更がありました。カート内の商品を確認ください！"
      end
      connect_token += (cart_item.lock_token + cart_item.quantity_in_cart.to_s + cart_item.product.price.to_s)
    end
    @long_token = CartItem.encrypt(connect_token)
  end

  def destroy
    @cart_item.destroy
    flash[:success] = "カートから#{@cart_item.product.title}を削除しました！"
    redirect_to cart_items_path
  end

  def update
    cart_item = current_user.cart_items.find_or_initialize_by(product_id: params[:cart_item][:product_id])
    origin_quantity = cart_item.quantity_in_cart
    asking_quantity = params[:cart_item][:quantity_in_cart].to_i
    cart_item.quantity_in_cart = asking_quantity

    if asking_quantity > cart_item.product.stock_quantity
      flash[:danger] = "#{cart_item.product.title}は在庫数が不足しています！
                        #{cart_item.product.title}は#{cart_item.product.stock_quantity}個まで購入できます."
    elsif !cart_item.save
      flash[:danger] = "購入希望数に1以上の整数を半角入力してください."
    else
      cart_item.create_lock_token
      flash[:success] = "#{cart_item.product.title}の希望購入数を
                        #{origin_quantity}個から#{asking_quantity}個に変更しました！"
    end
    return redirect_to cart_items_path
  end

  private
    def correct_user
      @cart_item = current_user.cart_items.find(params[:id])
    rescue
      redirect_to cart_items_path
    end

end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/views/cart_items/confirmation.html.erb
<% provide(:title, 'Confirmation') %>
<h1>注文商品確認</h1>

<h5>
  <%= render 'shared/notifications' %>
</h5>

<h5>
  <ul>
  <% sum = 0 %>
  <% @products.each do |product| %>
    <% cart_item = @cart_items.find_by(product_id: product.id) %>
      <% if cart_item.possible_quantity != 0%>
        <li>
          <%= link_to product.title, product %>

          価格: <%= product.price %>
          注文個数: <%= cart_item.possible_quantity %>
          小計: <%= product.price * cart_item.possible_quantity %>
          <% sum += product.price * cart_item.possible_quantity%>

        </li>
        <% end %>
  <% end %>
  </ul>
  合計 <%= sum %>円

  <% if sum != 0%>
    <%= form_for @order do |f| %>
      <%= f.label "送付先の住所選択" %>
      <%= f.collection_select :address_text, @addresses, :address_text, :address_text%>
      <%= f.submit "注文を確定する" %>
    <% end %>
  <% end %>

</h5>

app/views/cart_items/create.html.erb
<h1>CartItems#create</h1>
<p>Find me in app/views/cart_items/create.html.erb</p>

app/views/cart_items/destroy.html.erb
<h1>CartItems#destroy</h1>
<p>Find me in app/views/cart_items/destroy.html.erb</p>

app/views/cart_items/index.html.erb
<% provide(:title, 'All Cart Items') %>
<h1>カート内商品一覧</h1>

<% if @cart_items.count != 0 %>
  <h5>
    <ul>
    <% sum = 0 %>
    <% error = 0 %>
    <% @cart_items.includes(:product).each do |cart_item| %>
      <li>
        <%= link_to cart_item.product.title, cart_item.product %>
          <% if cart_item.price_in_cart == cart_item.product.price %>
              価格: <%= cart_item.price_in_cart %>円
          <% else %>
            <% if cart_item.price_in_cart == 0 %>
              価格: <%= cart_item.product.price %>円
            <% else %>
              <font color=Red>
              変更前価格: <%= cart_item.price_in_cart %>円
              変更後価格: <%= cart_item.product.price %>円
              </font>
            <% end %>
            <% cart_item.update_attribute(:price_in_cart, cart_item.product.price) %>
          <% end %>

          <% if cart_item.quantity_in_cart <= cart_item.product.stock_quantity %>
              購入希望数: <%= cart_item.quantity_in_cart %>個
              小計:<%= cart_item.product.price * cart_item.quantity_in_cart %>円
              <% sum += cart_item.product.price * cart_item.quantity_in_cart%>
          <% else %>
              <font color=Red>在庫数が購入希望数（<%= cart_item.quantity_in_cart %>個）以下です。
              現在の在庫数は<%= cart_item.product.stock_quantity %>個です。</font>
              <% error += 1 %>
          <% end %>

            <%= link_to "delete", cart_item_path(cart_item.id),
             method: :delete, data: { confirm: "You sure?" } %>

        <% if cart_item.product.stock_quantity !=0 %>
            <%= form_for(cart_item) do |f| %>
            <%= f.hidden_field :product_id, value: cart_item.product_id %>

            <%= f.number_field :quantity_in_cart, class: 'form-control', min:1, max:30%>
            <%= f.submit "購入希望数を変更する", class: "btn btn-large btn-primary" %>
            <% end %>
       <% end %>
      </li>
    <% end %>
    </ul>
    合計: <%= sum %>円
    <% if error == 0%>
      <%= form_tag((confirmation_path), method: :get) do %>
      <%= hidden_field_tag 'token', @long_token %>
      <%= submit_tag "注文内容確認" %>
      <% end %>
    <% elsif error != 0%>
      <font color=Red>商品の在庫数が希望購入数以下であるため、注文できません。
        該当商品を削除するか、希望購入数を在庫数以下に変更してください。</font>
    <% end %>
  </h5>
<% else @cart_items.count == 0 %>
  You don't have any items. Please check <%= link_to "Our items", root_url %>
<% end %>