config/routes.rb
Rails.application.routes.draw do

  get 'orders/create'

  root                      'products#index'
  get    'signup'       =>  'users#new'
  get    'signin'       =>  'sessions#new'
  post   'signin'       =>  'sessions#create'
  delete 'signout'      =>  'sessions#destroy'
  resources :users
  resources :products
  resources :cart_items,       only: [:index, :create, :destroy, :update]
  get    'confirmation' =>  'orders#new'
  post   'orders'       =>  'orders#create'

end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "shopping site", root_path %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "カート", cart_items_path %></li>

        <% if signed_in? %>
          <li><%= link_to "サインアウト", signout_path, method: "delete" %> </li>
        <% else %>
          <li><%= link_to "サインアップ", signup_path %></li>
          <li><%= link_to "サインイン", signin_path %></li>
        <% end %>

      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag 'application', media: 'all','data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>